AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Description: AWS CloudFormation loadbalancer template

Parameters:
  Env:
    Description: Enter dev, prod, test
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test

  ProjectName:
    Description: Enter project Name
    Type: String

  VpcCidr:
    Description: Enter VPC CIDR
    Type: String
    Default: 10.0.0.0/16

  DBInstanceName:
    Description: Enter db username
    Type: String

  DBUsername:
    Description: Enter username for Postgresql database 
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Default: 'postgres'

  DBPassword:
    Description: Enter password for Postgresql database 
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'

Mappings:
  AzMap:
    a:
      pub: 0
      priv: 1
    b:
      pub: 2
      priv: 3

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Stack
          Value: !Ref Env
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-vpc
  
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-igw

  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  NATGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
  
  NatGateWay:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubneta
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-nat

  PublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-public-rt

  PrivateRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-private-rt

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref PublicRT

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRT
      NatGatewayId: !Ref NatGateWay
      DestinationCidrBlock: 0.0.0.0/0

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub loadbalancer-security-group-${Env}
      GroupDescription: 'Allow HTTP/HTTPS inbound traffic and all outbound traffic'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub webapp-security-group-${Env}
      GroupDescription: 'Allow HTTP/HTTPS and SSH inbound and outbound traffic'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-webapp-sg

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub db-security-group-${Env}
      GroupDescription: Allow postgres inbound traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref WebAppSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-db-sg

  Fn::ForEach::AZ:
    - az
    - [a, b]

    - PublicSubnet${az}:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref VPC
          AvailabilityZone: !Sub ${AWS::Region}${az}
          CidrBlock: !Select 
            - !FindInMap [AzMap, !Ref az, pub]
            - !Cidr [ !Ref VpcCidr, 4, 8 ]
          Tags:
            - Key: Name
              Value: !Sub ${ProjectName}-${Env}-public-${az}-subnet

      PrivateSubnet${az}:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref VPC
          AvailabilityZone: !Sub ${AWS::Region}${az}
          CidrBlock: !Select 
            - !FindInMap [AzMap, !Ref az, priv]
            #- !Cidr [ !Ref VpcCidr, 4, 8 ]
            - !Cidr
              - !Ref VpcCidr
              - 4
              - 8  
          Tags:
            - Key: Name
              Value: !Sub ${ProjectName}-${Env}-private-${az}-subnet

      PublicSubnetAssociation${az}:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          RouteTableId: !Ref PublicRT
          SubnetId: !Ref
            "Fn::Sub": PublicSubnet${az}

      PrivateSubnetAssociation${az}:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          RouteTableId: !Ref PrivateRT
          SubnetId: !Ref 
            "Fn::Sub": PrivateSubnet${az}

      WebAppInstance${az}:
        Type: AWS::EC2::Instance
        DependsOn:
          - NatGateWay
          - DBInstance
        Properties: 
          ImageId: ami-0c7217cdde317cfec # Ubuntu 22.04 LTS
          InstanceType: t2.micro
          IamInstanceProfile: s3ReadOnlyEc2
          SubnetId: !Ref 
            "Fn::Sub": PrivateSubnet${az}
          SecurityGroupIds:
            - !Ref WebAppSecurityGroup
          UserData:
            Fn::Base64: !Sub |
              #!/bin/bash
              sudo su
              apt-get update -y
              apt-get upgrade -y

              apt-get install -y nginx php8.1-fpm composer

              rm -f /etc/nginx/sites-enabled/default
              rm -f /etc/nginx/sites-available/default
              
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              sudo apt-get install unzip -y
              unzip awscliv2.zip
              sudo ./aws/install
              
              aws s3 cp s3://amzn-s3-bucket-chatapp/nginx.conf /etc/nginx/sites-available/default
              
              ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

              apt-get install -y postgresql-client

              apt-get install php-pgsql -y
              composer require vlucas/phpdotenv  --no-interaction

              aws s3 cp s3://amzn-s3-bucket-chatapp/index.php /var/www/html/index.php 
              echo From machine ${az} >> /var/www/html/index.php

              cat > /var/www/html/.env << EOF
              DB_HOST=${DBInstance.Endpoint.Address}
              DB_PASSWORD=${DBPassword}
              EOF

              chmod -R 777 /var/www/html

              sudo systemctl restart nginx
          Tags:
            - Key: Name
              Value: !Sub ${ProjectName}-${Env}-webapp-${az}-instance
    
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-${Env}-alb
      Type: application
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubneta
        - !Ref PublicSubnetb
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-alb

  HTTPlistener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
  
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${ProjectName}-${Env}-tg
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: instance
      Targets:
        - Id: !Ref WebAppInstancea
          Port: 80
        - Id: !Ref WebAppInstanceb
          Port: 80
          
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref PrivateSubneta
        - !Ref PrivateSubnetb

  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceName
      AllocatedStorage: '5'
      Engine: postgres
      DBInstanceClass: db.t3.micro
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Sub ${DBPassword}
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-db-instance