AWSTemplateFormatVersion: 2010-09-09
Description: ECS template for apps

Parameters:
  ProjectName:
    Description: Enter project name
    Type: String

  AWSHostRegister:
    Description: Enter AWS host register
    Type: String
    
  SecretManagerArn:
    Description: Enter Secret Manager ARN
    Type: String

  SSM:
    Description: Enter SSM ARN
    Type: String

  TargetGroupArn:
    Description: Enter Target Group ARN
    Type: String
    
  PrivateSubnetaId:
    Description: Enter private subnet a ID
    Type: AWS::EC2::Subnet::Id
  
  PrivateSubnetbId:
    Description: Enter private subnet b ID
    Type: AWS::EC2::Subnet::Id

  WebAppSecurityGroupId:
    Description: Enter web app security group ID
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: '2048'
      Memory: '4096'
      TaskRoleArn: arn:aws:iam::919788038405:role/ECS-role-8ca6e49b
      ExecutionRoleArn: arn:aws:iam::919788038405:role/service-role/ecsTaskExecutionRole
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      EnableFaultInjection: false
      RuntimePlatform:
        OperatingSystemFamily: LINUX
        CpuArchitecture: X86_64

      ContainerDefinitions:
        - name: app
          image: !Sub ${AWSHostRegister}/${ProjectName}/app:latest
          cpu: 1024
          memory: 2048
          portMappings:
            - containerPort: 9000
              hostPort: 9000
              protocol: tcp
              name: app-9000-tcp
          essential: true
          environment:
            - name: username
              value: postgres
          secrets:
            - name: DB_HOST
              valueFrom: !Ref SSM
            - name: password
              valueFrom: !Sub "${SecretManagerArn}:password::"
  
        - name: nginx
          image: !Sub ${AWSHostRegister}/${ProjectName}/nginx:latest
          cpu: 1024
          memory: 2048
          portMappings:
            - containerPort: 80
              hostPort: 80
              protocol: tcp
              name: nginx-80-tcp
              appProtocol: http

            - containerPort: 8080
              hostPort: 8080
              protocol: tcp
              name: nginx-8080-tcp
              appProtocol: http
          essential: true
          DependsOn:
            - containerName: app
              condition: START
      
      Family: !Sub ${ProjectName}-taskdef

  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}-cluster
  
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Sub ${ProjectName}-cluster
      ServiceName: !Sub ${ProjectName}-service
      TaskDefinition: !Ref TaskDefinition
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      DesiredCount: 2
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroupArn
          ContainerName: nginx
          ContainerPort: 80
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PrivateSubnetaId
            - !Ref PrivateSubnetbId
          SecurityGroups:
            - !Ref WebAppSecurityGroupId
          AssignPublicIp: DISABLED
  
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    DependsOn: Service
    Properties:
      ServiceNamespace: ecs
      MaxCapacity: 4
      MinCapacity: 2
      ResourceId: !Sub "service/${ProjectName}-cluster/${ProjectName}-service"
      RoleARN: arn:aws:iam::919788038405:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService
      ScalableDimension: ecs:service:DesiredCount 
      
  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CPUUtilization
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleOutCooldown: 300
        ScaleInCooldown: 300