AWSTemplateFormatVersion: 2010-09-09
Description: RDS template for apps

Parameters:
  DBInstanceName:
    Description: Enter db username
    Type: String

  DBUsername:
    Description: Enter username for Postgresql database 
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Default: 'postgres'

  PrivateSubnetaId:
    Description: Enter private subnet a ID
    Type: AWS::EC2::Subnet::Id
  
  PrivateSubnetbId:
    Description: Enter private subnet b ID
    Type: AWS::EC2::Subnet::Id

  DBSecurityGroupId:
    Description: Enter database security group ID
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS instance
      SubnetIds:
        - !Ref PrivateSubnetaId
        - !Ref PrivateSubnetbId

  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This is the secret for RDS instance
      Name: !Sub ${DBInstanceName}-secret
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"$@/\'

  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceName
      AllocatedStorage: '5'
      Engine: postgres
      DBInstanceClass: db.t3.micro
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref Secret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref Secret, ':SecretString:password}}' ]]
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: 
        - !Ref DBSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub db-instance

  Parameter:
    Type: AWS::SSM::Parameter
    DependsOn: DBInstance
    Properties:
      Name: !Sub ${DBInstanceName}-parameter
      Type: String
      Value: !GetAtt DBInstance.Endpoint.Address

Outputs:
  SecretManagerArn:
    Description: Secret Manager ARN for RDS instance
    Value: !Ref Secret

  SSM:
    Description: SSM Name for RDS instance
    Value: !Ref Parameter