export const config = {
  APP_URL: window.APP_CONFIG.APP_URL,

  REST_ENDPOINT: window.APP_CONFIG.REST_ENDPOINT,
  WS_ENDPOINT: window.APP_CONFIG.WS_ENDPOINT,

  CONGITO_AUTHORITY: window.APP_CONFIG.CONGITO_AUTHORITY,
  CONGITO_CLIENT_ID: window.APP_CONFIG.CONGITO_CLIENT_ID,
  CONGITO_DOMAIN: window.APP_CONFIG.CONGITO_DOMAIN
}
