AWSTemplateFormatVersion: 2010-09-09
Description: Apps template

Parameters:
  InfraStackName:
    Description: Enter the name of the infra stack
    Type: String
    Default: infra

  S3BucketName:
    Description: Enter S3 bucket name
    Type: String
    Default: cloudformation5902
  
  AWSHostRegister:
    Description: Enter AWS host register
    Type: String
    Default: 919788038405.dkr.ecr.us-east-1.amazonaws.com

  DBInstanceName:
    Description: Enter db username
    Type: String
    Default: db-instance

  DBUsername:
    Description: Enter username for Postgresql database 
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    Default: 'postgres'

Resources:
  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.us-east-1.amazonaws.com/ecs/apps/sg.yml
      Parameters:
        ProjectName: !ImportValue 
          "Fn::Sub": ${InfraStackName}-ProjectName
        Env: !ImportValue 
          "Fn::Sub": ${InfraStackName}-Env
        VpcId: !ImportValue
          "Fn::Sub": ${InfraStackName}-VpcId
  
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SGStack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.us-east-1.amazonaws.com/ecs/apps/rds.yml
      Parameters:
        DBInstanceName: !Ref DBInstanceName
        DBUsername: !Ref DBUsername
        PrivateSubnetaId: !ImportValue 
          "Fn::Sub": ${InfraStackName}-PrivateSubnetaId
        PrivateSubnetbId: !ImportValue 
          "Fn::Sub": ${InfraStackName}-PrivateSubnetbId
        DBSecurityGroupId: !GetAtt SGStack.Outputs.DBSecurityGroupId

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.us-east-1.amazonaws.com/ecs/apps/alb.yml
      Parameters:
        ProjectName: !ImportValue
          "Fn::Sub": ${InfraStackName}-ProjectName
        Env: !ImportValue 
          "Fn::Sub": ${InfraStackName}-Env
        PublicSubnetaId: !ImportValue 
          "Fn::Sub": ${InfraStackName}-PublicSubnetaId
        PublicSubnetbId: !ImportValue 
          "Fn::Sub": ${InfraStackName}-PublicSubnetbId
        LoadBalancerSecurityGroupId: !GetAtt SGStack.Outputs.LoadBalancerSecurityGroupId
        VpcId: !ImportValue
          "Fn::Sub": ${InfraStackName}-VpcId

  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - RDSStack
      - ALBStack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.s3.us-east-1.amazonaws.com/ecs/apps/ecs.yml
      Parameters:
        ProjectName: !ImportValue
          "Fn::Sub": ${InfraStackName}-ProjectName
        AWSHostRegister: !Ref AWSHostRegister
        SecretManagerArn: !GetAtt RDSStack.Outputs.SecretManagerArn
        SSM: !GetAtt RDSStack.Outputs.SSM
        TargetGroupArn: !GetAtt ALBStack.Outputs.TargetGroupARN
        PrivateSubnetaId: !ImportValue 
          "Fn::Sub": ${InfraStackName}-PrivateSubnetaId
        PrivateSubnetbId: !ImportValue 
          "Fn::Sub": ${InfraStackName}-PrivateSubnetbId
        WebAppSecurityGroupId: !GetAtt SGStack.Outputs.WebAppSecurityGroupId