AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB table template for apps

Parameters:
  ProjectName:
    Description: Enter project Name
    Type: String

  Env:
    Description: Enter dev, prod, test
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-${Env}-table
      AttributeDefinitions:
        - AttributeName: FileKey
          AttributeType: S
        - AttributeName: Timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: FileKey
          KeyType: HASH
        - AttributeName: Timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-table