AWSTemplateFormatVersion: 2010-09-09
Description: Lambda function template for apps
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Description: Enter project Name
    Type: String

  Env:
    Description: Enter dev, prod, test
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test
  
  SQSQueueArn:
    Description: Enter SQS queue ARN
    Type: String

  PrivateSubnetaId:
    Description: Enter private subnet a id
    Type: String

  PrivateSubnetbId:
    Description: Enter private subnet b id
    Type: String

  DefultSgId:
    Description: Enter default security group ID
    Type: String

  VpcId:
    Description: Enter VPC ID
    Type: String

  S3AssetsBucketName:
    Description: Enter S3 bucket assets name
    Type: String

Resources:
  LambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${Env}-lambda-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${ProjectName}-${Env}-dynamodb-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ReadWriteTable
                Effect: Allow
                Action:
                  - dynamodb:BatchWriteItem
                  - dynamodb:Scan
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchGetItem
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource: "*"
        - PolicyName: !Sub "${ProjectName}-${Env}-sqs-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: SQSAccess
                Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: "*"
        - PolicyName: !Sub "${ProjectName}-${Env}-vpc-policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: LambdaVPCAccess
                Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - ec2:AssignPrivateIpAddresses
                  - ec2:UnassignPrivateIpAddresses
                Resource: "*"

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ProjectName}-${Env}-function
      Runtime: python3.12
      CodeUri: 
        Bucket: !Ref S3AssetsBucketName
        Key: serverless/app/lambda.zip
      Handler: lambda.lambda_handler
      Role: !GetAtt LambdaFunctionRole.Arn
      Timeout: 4
      VpcConfig:
        SubnetIds:
          - !Ref PrivateSubnetaId
          - !Ref PrivateSubnetbId
        SecurityGroupIds:
          - !Ref DefultSgId
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref SQSQueueArn
            BatchSize: 10