AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Description: Infra template

Parameters:
  S3AssetsBucketName:
    Description: Enter S3 bucket assets name
    Type: String
    Default: cloudformation5902

  ProjectName:
    Description: Enter project Name
    Type: String
    Default: filemanager

  Env:
    Description: Enter dev, prod, test
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test
  
  VpcCidr:
    Description: Enter VPC CIDR
    Type: String
    Default: 10.0.0.0/16

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3AssetsBucketName}.s3.us-east-1.amazonaws.com/serverless/infra/vpc.yml
      Parameters:
        ProjectName: !Ref ProjectName
        Env: !Ref Env
        VpcCidr: !Ref VpcCidr

Outputs:
  ProjectName:
    Description: The project name
    Value: !Ref ProjectName
    Export:
      Name:
        "Fn::Sub": ${AWS::StackName}-ProjectName

  Env:
    Description: Env
    Value: !Ref Env 
    Export:
      Name:
        "Fn::Sub": ${AWS::StackName}-Env

  VpcCidr:
    Description: The VPC CIDR block
    Value: !GetAtt VPCStack.Outputs.Cidr
    Export:
      Name:
        "Fn::Sub": ${AWS::StackName}-VpcCidr

  VpcId:
    Description: The VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name:
        "Fn::Sub": ${AWS::StackName}-VpcId

  DefultSgId:
      Description: The default security group ID of the VPC
      Value: !GetAtt VPCStack.Outputs.DefultSgId
      Export:
        Name:
          "Fn::Sub": ${AWS::StackName}-DefultSgId

  Fn::ForEach::AZ:
    - az
    - [a, b]

    - VPCPrivateSubnet${az}Id:
        Description: !Sub The Private Subnet ID for AZ ${az}
        Value: !GetAtt 
          - VPCStack
          - !Sub 'Outputs.PrivateSubnet${az}Id'
        Export:
          Name:
            "Fn::Sub": ${AWS::StackName}-PrivateSubnet${az}Id