AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::LanguageExtensions
Description: VPC template for infra 

Parameters:
  ProjectName:
    Description: Enter project Name
    Type: String

  Env:
    Description: Enter dev, prod, test
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
      - test
  
  VpcCidr:
    Description: Enter VPC CIDR
    Type: String
    Default: 10.0.0.0/16

Mappings:
  AzMap:
    a:
      priv: 0
    b:
      priv: 1

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-vpc
  
  PrivateRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-private-rt

  DynamodbEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      VpcId: !Ref VPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
      RouteTableIds:
        - !GetAtt PrivateRT.RouteTableId
      PolicyDocument: '{
        "Version":"2008-10-17",
        "Statement": [{
          "Effect":"Allow",
          "Principal":"*",
          "Action":["*"],
          "Resource":"*"
        }]
      }'
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Env}-dynamodb-endpoint

  Fn::ForEach::AZ:
    - az
    - [a, b]

    - PrivateSubnet${az}:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref VPC
          AvailabilityZone: !Sub ${AWS::Region}${az}
          CidrBlock: !Select 
            - !FindInMap [AzMap, !Ref az, priv]
            - !Cidr [ !Ref VpcCidr, 2, 8 ]
          Tags:
            - Key: Name
              Value: !Sub ${ProjectName}-${Env}-private-${az}-subnet

      PrivateSubnetAssociation${az}:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          RouteTableId: !Ref PrivateRT
          SubnetId: !Ref 
            "Fn::Sub": PrivateSubnet${az}

Outputs:
  Cidr:
    Description: The VPC CIDR block
    Value: !Ref VpcCidr

  VpcId:
    Description: The VPC ID
    Value: !Ref VPC

  DefultSgId:
    Value: !GetAtt  VPC.DefaultSecurityGroup

  Fn::ForEach::AZOutput:
    - az
    - [a, b]

    - PrivateSubnet${az}Id:
        Description: The Private Subnet ID for AZ ${az}
        Value:
          Ref:
            "Fn::Sub": PrivateSubnet${az}
